#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=90
INTERFACE=br-lan
PORT=1337

# check if configuration exists
[ -e "/etc/bdix.conf" ] || exit 0

iptable_start() {
    /bin/echo -n "running bdix iptables ..."

    # Run iptable commands
    iptables -t nat -N BDIX

    # Direct connections for specific domains
    iptables -t nat -A BDIX -d ad.com -j REJECT
    iptables -t nat -A BDIX -d analytics.google.com -j REJECT
    iptables -t nat -A BDIX -d analyticsinsights-pa.googleapis.com -j REJECT
    iptables -t nat -A BDIX -d analyticsreporting.googleapis.com -j REJECT
    iptables -t nat -A BDIX -d doubleclick.net -j REJECT
    iptables -t nat -A BDIX -d googleadservices.com -j REJECT
    iptables -t nat -A BDIX -d googleadsserving.cn -j REJECT
    iptables -t nat -A BDIX -d googlesyndication.com -j REJECT
    iptables -t nat -A BDIX -d googletagmanager.com -j REJECT
    iptables -t nat -A BDIX -d googletagservices.com -j REJECT
    iptables -t nat -A BDIX -d google-analytics.com -j REJECT
    iptables -t nat -A BDIX -d tracker.torrent.eu.org -j REJECT
    iptables -t nat -A BDIX -d tracker.opentrackr.org -j REJECT
    iptables -t nat -A BDIX -d open.stealth.si -j REJECT
    iptables -t nat -A BDIX -d exodus.desync.com -j REJECT
    iptables -t nat -A BDIX -d ggpht.com -j REJECT
    iptables -t nat -A BDIX -d nyaa.tracker.wf -j REJECT
    iptables -t nat -A BDIX -d adservice -j REJECT
    iptables -t nat -A BDIX -d analytics -j REJECT
    iptables -t nat -A BDIX -d analysis -j REJECT
    iptables -t nat -A BDIX -d googleads -j REJECT
    iptables -t nat -A BDIX -d facebook -j REJECT
    iptables -t nat -A BDIX -d torrentbd -j REJECT
    iptables -t nat -A BDIX -d fbcdn -j REJECT
    iptables -t nat -A BDIX -d youtube -j REJECT
    iptables -t nat -A BDIX -d googlevideo -j REJECT
    iptables -t nat -A BDIX -d discoveryftp -j REJECT
    iptables -t nat -A BDIX -d circleftp -j REJECT
    iptables -t nat -A BDIX -s 192.168.1.201/32 -j RETURN
    iptables -t nat -A BDIX -d telegram.org -j RETURN
    iptables -t nat -A BDIX -d whatsapp.com -j RETURN
    iptables -t nat -A BDIX -d speedtest.net -j RETURN
    iptables -t nat -A BDIX -d speedtest.com.sg -j RETURN
    iptables -t nat -A BDIX -d 172.16.50.4 -j RETURN


    iptables -t nat -A BDIX -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A BDIX -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A BDIX -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A BDIX -d 169.254.0.0/16 -j RETURN
#    iptables -t nat -A BDIX -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A BDIX -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A BDIX -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A BDIX -d 240.0.0.0/4 -j RETURN

    iptables -t nat -A BDIX -p tcp -j REDIRECT --to-ports ${PORT}

    iptables -t nat -A PREROUTING -i ${INTERFACE} -p tcp -j BDIX

    iptables -A INPUT -i br-lan -p tcp --dport ${PORT} -j ACCEPT

    /bin/echo " done"
}

iptable_stop() {
    /bin/echo -n "cleaning bdix iptables ..."

    # Run iptable commands
    iptables -t nat -F BDIX
    iptables -t nat -F PREROUTING
    iptables -t nat -F POSTROUTING
    iptables -F INPUT
    iptables -F FORWARD
    iptables -t nat -X BDIX

    /bin/echo " done"
}

start() {
    if [ -e "/var/run/bdix.pid" ]; then
        echo "bdix is already running"
        exit 0
    fi

    /bin/echo -n "running bdix ..."

    # startup the safety-wrapper for the daemon
    /usr/sbin/redsocks -c /etc/bdix.conf -p /var/run/bdix.pid

    /bin/echo " done"
    iptable_start
}


stop() {
    if [ ! -e "/var/run/bdix.pid" ]; then
        echo "bdix is not running"
        exit 0
    fi

    /bin/echo -n "stopping bdix ..."

    # kill the process
    /bin/kill $(cat /var/run/bdix.pid)
    rm /var/run/bdix.pid

    echo " done"
    iptable_stop

    /bin/echo -n "restarting firewall ..."
    /etc/init.d/firewall restart &> /dev/null
    /bin/echo " done"
}
